#include "cpu.h"
#include "qencode.h"
#include <stdio.h>

/* ROM File to read, generated by Assembler */ 
#define ROM_PATH "./bin/counter.bin" 

extern int RUN;

int main(void){
    CPU* cpu = cpu_init();
    MemByte* mem = mem_init();

    FILE* rom_file = fopen(ROM_PATH,"rb");

    if(rom_file){ // If File Exists
        fread(mem,WORD,PROG_MAX,rom_file);
        fclose(rom_file);
        while(RUN){
            fetch(cpu,mem);
            decode(cpu);
            execute(cpu,mem);
        }
    }
    else{
        fprintf(stderr,"Cant Locate Rom File...\n");
    }

    fflush(stdout);
    cpu_free(&cpu);
    mem_free(&mem);
    return 0;
}

